[package]
name = "windows-driver-library"
version = "0.1.0"
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
wdk.workspace = true
wdk-alloc.workspace = true
wdk-panic.workspace = true
wdk-sys.workspace = true

[build-dependencies]
anyhow.workspace = true
wdk-build.workspace = true
cbindgen = "0.27.0"

[lib]
crate-type = ["staticlib"]

[features]
default = []
nightly = ["wdk/nightly", "wdk-sys/nightly"]
